# Generated by Django 4.0.4 on 2022-05-21 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_group', models.CharField(max_length=30, verbose_name='Введите введите учебную группу')),
            ],
            options={
                'verbose_name': 'Учебная группа',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Введите уникальный номер студента')),
                ('first_name', models.CharField(max_length=30, verbose_name='Введите имя студента')),
                ('patronymic_name', models.CharField(max_length=30, verbose_name='Введите отчетство студента')),
                ('last_name', models.CharField(max_length=30, verbose_name='Введите фамилию студента')),
                ('date_of_birth', models.DateField(verbose_name='Введите дату рождения')),
                ('study_group', models.ForeignKey(help_text='Выберите учебную группу', on_delete=django.db.models.deletion.CASCADE, to='students1.studygroup')),
            ],
            options={
                'verbose_name': 'Данные студента',
            },
        ),
    ]
